### ISSUE TITLE
ReCAPTCHA?

### ISSUE THREAD

**Issue by drinfernoo** [doko-desuka/doko-desuka.github.io#2]
Does your repo require a CAPTCHA now or something?

**Comment by doko-desuka** [comment]
Hi.
No, I needed a place to test captcha solving in-browser, and you can only have one single Github Pages project (it lets you host web pages accessible by browsers).
So I used the "doko-desuka.github.io" site to host those files, but they're for testing only and inaccessible to people that use my repo, because they're not linked anywhere (you only know about it because you follow it or saw it on my activity, probably).

edit: I'm still not done testing them btw, there's nothing useful in them, I'll get back to them later.
